### ISSUE TITLE
Template script error in IE11

### ISSUE THREAD

**Issue by jillande** [NDSU-Information-Technology/ndsu-web-template#10]
Console message:
SCRIPT5009: 'Promise' is undefined
script.min.js (8,826)

(this is at
t=new Promise(function(e,t){try{var n=new Audio,i=n.canPlayType("audio/ogg") ...)

The script error results in navigation menus not working on IE11, so visitors aren't able to get to Provost subpages at www.ndsu.edu/provost/ .

**Comment by twinfifty** [comment]
I tested the page on IE11 running on Windows 10, it works fine. When I switch it to  **IE10** compatibility mode, I see the error.

**Comment by twinfifty** [comment]
Scratch my previous comment, now I do see it.

**Comment by twinfifty** [comment]
Fixed with polyfill addition in dc0e496664aac1b79cdb55c4ea45c3432292f346
