### ISSUE TITLE
Navbar menu missing "current" style

### ISSUE THREAD

**Issue by jillande** [NDSU-Information-Technology/ndsu-web-template#4]
The current page displayed should not be a link to itself in the navbar. That text (with whatever wrapper is used) should be styled in a way that makes it clear to the visitor that the text is not a clickable link.

**Comment by twinfifty** [comment]
Related to #5 

There is already a css class, `.active` that can be added to a `.nav-link` item to mark it as a "current" item (i.e. `.nav-link.active`).

For disabling link to current page, along with #5 (adding style to active branch or "rootline"), this would be good for discussion whether we should add these as default features of the template.

For some CMS like Typo3, there is an easy way to access current page and its rootline. For others, like Jekyll, there may be system limitations (Liquid engine in case of Jekyll) that there is no reliable way to tell the current page and/or the branch a page is located in. There are also be cases where, by terrible design/organization, one page may have multiple links directing to it on a navigation.

In my opinion, I think we should leave to the developers to implement these features on their own system.

**Comment by jillande** [comment]
I'm not suggesting that we should automatically figure out what is the current rootline, but to have a class that can be applied (by the developer who has knowledge of the rootline) to the active branch.

**Comment by jillande** [comment]
If .active should be used for the current page (that should not be a link), it needs enhancements to take away the clickable cues like the changed cursor if it's not actually clickable (because it's not a link). See, for example, https://cms-devel.it.ndsu.edu/index.php?id=4 .

**Comment by twinfifty** [comment]
https://ndsu-information-technology.github.io/ndsu-web-template/components/navbar/#indicating-current-page-and-branch
