### ISSUE TITLE
Top of content section is hidden by the fixed menu when navigating to an in-page anchor

### ISSUE THREAD

**Issue by jillande** [NDSU-Information-Technology/ndsu-web-template#6]
An example of this problem is demonstrated on the "Bachelor of Science" sample page:
https://ndsu-information-technology.github.io/ndsu-web-template/sample-pages/department/degrees/undergraduates/bs/#content

This would occur in other instances of in-page navigation as well; it's not limited to the "Skip to page content" -> id="content" anchor.

**Comment by jillande** [comment]
The proposed fix seems to only address the "Skip to page content" case, not the general case of an in-page anchor. For example, https://cms-devel.it.ndsu.edu/eci/1-column-without-menu/#c23 or by using an in-page section list https://cms-devel.it.ndsu.edu/eci/1-column-with-menu/ .

**Comment by twinfifty** [comment]
Addressed in 600670bd9c6a74473f9e1bc0a4610ceabe894064
