### ISSUE TITLE
.row rules don't permit responsive linearizing of columns on small screens

### ISSUE THREAD

**Issue by jillande** [NDSU-Information-Technology/ndsu-web-template#8]
Content should be able to behave responsively so that it can display across more grids (e.x., full-width) on small devices where multiple columns aren't readable.

As example, https://cms-devel.it.ndsu.edu/provost/contact/ (note I tried substituting for the "column" class instead of the Bootstrap column names without any change to the linearizing behavior - https://cms-devel.it.ndsu.edu/cs/about/ ).

**Comment by twinfifty** [comment]
added media query to column sizes (e.g. col-**xs**-12), it should fix compatibility the issue above.
